function gamma = gamma_fcn_sec5(in1)
%GAMMA_FCN_SEC5
%    GAMMA = GAMMA_FCN_SEC5(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    05-Sep-2016 09:39:01

dxd1 = in1(3,:);
dxd2 = in1(7,:);
dxd3 = in1(11,:);
dxd4 = in1(15,:);
dxd5 = in1(19,:);
dxd6 = in1(23,:);
dxv1 = in1(1,:);
dxv2 = in1(5,:);
dxv3 = in1(9,:);
dxv4 = in1(13,:);
dxv5 = in1(17,:);
dxv6 = in1(21,:);
dyd1 = in1(4,:);
dyd2 = in1(8,:);
dyd3 = in1(12,:);
dyd4 = in1(16,:);
dyd5 = in1(20,:);
dyd6 = in1(24,:);
dyv1 = in1(2,:);
dyv2 = in1(6,:);
dyv3 = in1(10,:);
dyv4 = in1(14,:);
dyv5 = in1(18,:);
dyv6 = in1(22,:);
t2 = dxd1-dxv2;
t3 = dxd2-dxv1;
t4 = dyd1-dyv2;
t5 = dyd2-dyv1;
t6 = dxd2-dxv3;
t7 = dxd3-dxv2;
t8 = dyd2-dyv3;
t9 = dyd3-dyv2;
t10 = dxd3-dxv4;
t11 = dxd4-dxv3;
t12 = dyd3-dyv4;
t13 = dyd4-dyv3;
t14 = dxd4-dxv5;
t15 = dxd5-dxv4;
t16 = dyd4-dyv5;
t17 = dyd5-dyv4;
t18 = dxd5-dxv6;
t19 = dxd6-dxv5;
t20 = dyd5-dyv6;
t21 = dyd6-dyv5;
gamma = [dxd1.*t5-dxd2.*t4+dxv1.*t4-dxv2.*t5-dyd1.*t3+dyd2.*t2-dyv1.*t2+dyv2.*t3;dxd2.*t9-dxd3.*t8+dxv2.*t8-dxv3.*t9-dyd2.*t7+dyd3.*t6-dyv2.*t6+dyv3.*t7;dxd3.*t13-dxd4.*t12+dxv3.*t12-dxv4.*t13-dyd3.*t11+dyd4.*t10-dyv3.*t10+dyv4.*t11;dxd4.*t17-dxd5.*t16+dxv4.*t16-dxv5.*t17-dyd4.*t15+dyd5.*t14-dyv4.*t14+dyv5.*t15;dxd5.*t21-dxd6.*t20+dxv5.*t20-dxv6.*t21-dyd5.*t19+dyd6.*t18-dyv5.*t18+dyv6.*t19;0.0;0.0;0.0];
