function gamma = gamma_fcn_sec1(in1)
%GAMMA_FCN_SEC1
%    GAMMA = GAMMA_FCN_SEC1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    11-Sep-2016 09:40:54

dxd1 = in1(3,:);
dxd2 = in1(7,:);
dxv1 = in1(1,:);
dxv2 = in1(5,:);
dyd1 = in1(4,:);
dyd2 = in1(8,:);
dyv1 = in1(2,:);
dyv2 = in1(6,:);
t2 = dxd1-dxv2;
t3 = dxd2-dxv1;
t4 = dyd1-dyv2;
t5 = dyd2-dyv1;
gamma = [dxd1.*t5-dxd2.*t4+dxv1.*t4-dxv2.*t5-dyd1.*t3+dyd2.*t2-dyv1.*t2+dyv2.*t3;0.0;0.0;0.0];
